[package]
name = "finql"
version = "0.8.0-dev"
authors = ["Mark Beinker <mwb@quantlink.de>"]
edition = "2018"
description = "A quantitative finance toolbox"
license = "MIT OR Apache-2.0"
repository = "https://github.com/xemwebe/finql"
readme = "README.md"
keywords = ["finance", "calendar", "bond", "period", "pricing"]
categories = ["date-and-time","mathematics"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
text_io = "0.1"
computus = "1.0"
serde = { version = "1.0.*", features = ["derive"] }
serde_json = "1.0"
argmin = "0.4"
yahoo_finance_api = "1.1"
gurufocus_api = "0.4"
rand = "0.8"
eodhistoricaldata_api =  "0.3"
alpha_vantage = "0.5"
reqwest = "0.11"
scraper = "0.12"
csv = "1.1"
async-trait = "0.1"
tokio-compat-02 = "0.2"
finql-data = { version="0.1", path="finql-data" }

[dev-dependencies]
tokio = { version = "1.2", features =  ["macros"] }
tokio-test = "0.4"
rusqlite = "0.24"
finql-sqlite = { version="0.2", path = "finql-sqlite" }
sqlx = { path = "../sqlx1", default-features = false, features = [ "runtime-tokio", "migrate", "postgres", "sqlite" ] }
